title: Ci "Charles" Song # your name (or website title) here
logo: "/images/C_Song_portrait.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Student, Geospatial Data Science<br>
  MS Student, Data Science 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/songci/">View My LinkedIn Profile</a> 
  <br><br>
  <a herf="https://github.com/CiSong10">View My GitHub Profile</a>

plugins:
- jekyll-remote-theme
google_analytics: G-8CHHREXJP4 # your Google Analytics tracking ID here
