title: Ci "Charles" Song # your name (or website title) here
logo: "/images/C_Song_portrait.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Student, Geospatial Data Science<br>
  MS Student, Data Science 
  <br><br>
  I am passionate about pursuing an environment and sustainability world through the application of my skills in spatial analysis and data science.

  <br><br>
  <a href="https://www.linkedin.com/in/songci/">View My LinkedIn Profile</a> 


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-8CHHREXJP4 # your Google Analytics tracking ID here
